# Generated by Django 4.0.3 on 2024-06-21 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('user_nickname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('user_birth', models.DateTimeField()),
                ('user_gender', models.CharField(max_length=1)),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('del_yn', models.CharField(default='N', max_length=1)),
                ('auto_login_yn', models.CharField(default='N', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('activity_level_seq', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=45)),
                ('level_desc', models.CharField(max_length=200)),
                ('level_weight', models.FloatField()),
            ],
            options={
                'db_table': 'activity_level',
            },
        ),
        migrations.CreateModel(
            name='DietPeriod',
            fields=[
                ('diet_period_seq', models.AutoField(primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('goal_dt', models.DateTimeField()),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('goal_weight', models.FloatField(default=0.0)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('bmr', models.IntegerField(blank=True, null=True)),
                ('tdee', models.IntegerField(blank=True, null=True)),
                ('total_kcal', models.IntegerField(blank=True, null=True)),
                ('daily_kcal', models.IntegerField(blank=True, null=True)),
                ('daily_carbo', models.IntegerField(blank=True, null=True)),
                ('daily_protein', models.IntegerField(blank=True, null=True)),
                ('daily_prov', models.IntegerField(blank=True, null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
                ('stop_dt', models.DateTimeField(blank=True, null=True)),
                ('user_seq', models.ForeignKey(db_column='user_seq', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_period',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='activity_level_seq',
            field=models.ForeignKey(blank=True, db_column='activity_level_seq', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.activitylevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
