# Generated by Django 4.0.3 on 2024-06-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiet',
            fields=[
                ('daily_diet_seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('kcal', models.IntegerField()),
                ('carbo', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('prov', models.IntegerField()),
                ('success_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'daily_diet',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('kcal', models.IntegerField()),
                ('carbo', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('prov', models.IntegerField()),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
                ('mod_at', models.DateTimeField(blank=True, null=True)),
                ('food_img', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('daily_diet_seq', models.ForeignKey(db_column='daily_diet_seq', on_delete=django.db.models.deletion.CASCADE, to='diet.dailydiet')),
            ],
            options={
                'db_table': 'diet',
            },
        ),
    ]
