# Generated by Django 5.0.6 on 2024-06-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('kcal', models.IntegerField()),
                ('carbo', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('prov', models.IntegerField()),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='FoodAmount',
            fields=[
                ('food_amount_seq', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=45, unique=True)),
                ('level_weight', models.FloatField()),
            ],
            options={
                'db_table': 'food_amount',
            },
        ),
        migrations.AlterField(
            model_name='dailydiet',
            name='success_yn',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
