# Generated by Django 5.0.6 on 2024-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_food_foodamount_alter_dailydiet_success_yn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodAmount',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
